export const dataAllProduct = [
    {
        id: 1,
        product_name: 'Iphone 14 Pro Max 128GB',
        product_slug: "iphone-14-pro-max-128gb",
        product_img: require('../assets/product/iphone-14-pro-max.png'),
        product_price: '1060.99',
        product_old_price: '1080.99',
        product_reviews: '1234',
        product_sale_off: "40",
        product_manufacture: "apple",
        product_category: "phone",
        product_capacity: 128
    },
    {
        id: 2,
        product_name: 'Iphone 13 Pro Max 256GB',
        product_slug: "iphone-13-pro-max-256gb",
        product_img: require('../assets/product/iphone-13-pro-max-sierra-blue.png'),
        product_price: '1045.99',
        product_old_price: '1040.99',
        product_reviews: '1234',
        product_sale_off: "10",
        product_manufacture: "apple",
        product_category: "phone",
        product_capacity: 256
    },
    {
        id: 3,
        product_name: 'Ipad Pro 2021',
        product_slug: "ipad-pro-2021",
        product_img: require('../assets/product/ipad-pro-2021-129-inch-silver.png'),
        product_price: '1029.99',
        product_old_price: '1019.99',
        product_reviews: '1234',
        product_sale_off: "30",
        product_manufacture: "apple",
        product_category: "tablet",
        product_capacity: 128
    },
    {
        id: 4,
        product_name: 'Iphone 13 256GB',
        product_slug: "iphone-13-256gb",
        product_img: require('../assets/product/iphone-13-pink.png'),
        product_price: '1049.99',
        product_old_price: '39.99',
        product_reviews: '1234',
        product_sale_off: "10",
        product_manufacture: "apple",
        product_category: "phone",
        product_capacity: 256
    },
    {
        id: 5,
        product_name: 'Macbook Pro 13 inch M2 256GB',
        product_slug: "macbook-pro-13-inch-m2-256gb",
        product_img: require('../assets/product/macbook-pro-13-inch-m2-2022-gray.png'),
        product_price: '999.99',
        product_old_price: '',
        product_reviews: '1234',
        product_sale_off: "0",
        product_manufacture: "apple",
        product_category: "laptop",
        product_capacity: [256, 'M2']
    },
    {
        id: 6,
        product_name: 'Ipad 4 Cellular 4G',
        product_slug: "ipad-4-cellular-4g",
        product_img: require('../assets/product/ipad-4-cellular-white-4g.png'),
        product_price: '699.99',
        product_old_price: '750.99',
        product_reviews: '1234',
        product_sale_off: "0",
        product_manufacture: "apple",
        product_category: "ipad",
        product_capacity: 32
    },
    {
        id: 7,
        product_name: 'Iphone 11 64Gb',
        product_slug: "iphone-11-64gb",
        product_img: require('../assets/product/iphone-11-green.png'),
        product_price: '499.99',
        product_old_price: '',
        product_reviews: '1234',
        product_sale_off: "0",
        product_manufacture: "apple",
        product_category: "phone",
        product_capacity: 64
    },
    {
        id: 1,
        product_name: 'Iphone 14 Pro Max 256GB',
        product_slug: "iphone-14-pro-max-256gb",
        product_img: require('../assets/product/iphone-14-pro-max.png'),
        product_price: '1060.99',
        product_old_price: '1080.99',
        product_reviews: '1234',
        product_sale_off: "40",
        product_manufacture: "apple",
        product_category: "phone",
        product_capacity: 256
    },
]